### ISSUE TITLE
Does this plugin add other metadata like frame depth, height, width, channels etc to the gst buffer ?

### ISSUE THREAD

**Issue by sandeshk1** [WKDSMRT/realsense-gstreamer#20]

**Comment by TimConnelly** [comment]
That information is added to the header stored within the buffer itself. See https://github.com/WKDSMRT/realsense-gstreamer/blob/4c11e3d64ae67fea84db77145743db8522d3989a/src/common.hpp#L38

**Comment by sandeshk1** [comment]
It is possible to add these info to the gst meta struct ? Any reason why it is not added to gst meta ?

**Comment by sandeshk1** [comment]
why is get_distance (int x, int y) function not called on the depth frame ?

I see only get_units() is called on the depth frame.

**Comment by TimConnelly** [comment]
> It is possible to add these info to the gst meta struct ? Any reason why it is not added to gst meta ?

The information you're asking for is already part of the required GstMapInfo. GstMeta is for adding custom metadata that would otherwise not be a part of video/audio.

> why is get_distance (int x, int y) function not called on the depth frame ?

`get_distance` is an analysis function. This plugin is a source, only providing the data for downstream use. `get_distance` should be called in a downstream module where you implement your processing of the depth frame.
